<a href="https://colab.research.google.com/github/niranjan2399/Learning_PyTorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
print(torch.__version__)

2.8.0+cu126


In [6]:
#scalar
scalar = torch.tensor(2)
scalar

tensor(2)

In [9]:
# get dimension
scalar.ndim

0

In [10]:
#get tensor back as python int
scalar.item()

2

In [11]:
#vector
vector = torch.tensor([4,5])
vector

tensor([4, 5])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [23]:
#matrix
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
MATRIX[0]

tensor([7, 8])

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#tensor
TENSOR = torch.tensor([[[1,2,3], [3,4,5], [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

##Random Tensors

Random tensors are imp because the way many neural network learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

In [30]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3154, 0.0746, 0.7599, 0.1834],
         [0.9816, 0.4043, 0.3134, 0.3783],
         [0.0339, 0.5833, 0.0073, 0.2455]]])

In [31]:
random_tensor.ndim

3

In [38]:
#create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channels (r,g b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)